### ISSUE TITLE
Typo in line 1915 of unicodefonttable.dtx

### ISSUE THREAD

**Issue by sayahna** [FrankMittelbach/fmitex-unicodefonttable#10]
The word "Malayalam" is wrongly spelt as "Malayalm". Would you kindly correct it?

Line 1915:  { "0D0 }{ Malayalm }  =>  { "0D0 }{ Malayalam }

**Comment by FrankMittelbach** [comment]
thanks, sure. With the next update.

**Comment by FrankMittelbach** [comment]
uploaded to CTAN, should appear during the next days in the distributions
