### ISSUE TITLE
Alternate hex-digit format

### ISSUE THREAD

**Issue by kess** [FrankMittelbach/fmitex-unicodefonttable#3]
The hex-digits in the first column are by default shown as something similar to `U+0020 - 002F`:

```
\cs_new:Npn \@@_format_row_title:n #1 {
  \texttt { \footnotesize \l_@@_color_tl U+#1 0 \, - \, #1 F }
}
```

I suggest a new key–value that makes it possible to directly tweak this command. Personally I have used the following three formats:

* `U+0020–002F`
* `U+002`
* `002`

In the first example the space encapsulated dash is turned into a proper n-dash. The second and third examples are more compact and common in texts where an awareness of codecharts is assumed.

**Comment by FrankMittelbach** [comment]
One of the (many) possible enhancements, I'll see if I can fit that in at some point. Thanks  for the suggestion

**Comment by FrankMittelbach** [comment]
Added `hex-digits-row-format` in the next release to allow customization.
