### ISSUE TITLE
Not compatible with the standalone class?

### ISSUE THREAD

**Issue by jsbien** [FrankMittelbach/fmitex-unicodefonttable#6]
[standalone.zip](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9936989/standalone.zip)
The range selected doesn't seem relevant, works OK with the article class.

**Comment by FrankMittelbach** [comment]
sorry, given that it works with article, wouldn't that be most likely an issue with "standalone"?

Indeed it is: standalone assumes that you produce a single page and that is obviously not the case here.
```
Using \documentclass[multi=true]{standalone}
```
does not give errors but still doesn't look right and is not producing several cropped pages. My guess is that standalone is not compatible with longtable, or only with a suitable option setting. In any case that low-level error is something I think you need to pursue with Martin as it is clearly a standalone issue -- so I'm going to close here.

**Comment by jsbien** [comment]
OK
