### ISSUE TITLE
Bad table content

### ISSUE THREAD

**Issue by jsbien** [FrankMittelbach/fmitex-unicodefonttable#8]
This actually a follow-up to #7.
With  `range-end=F005F` the output is bad, with `range-end=FFFFF` the output is OK with XeTeX, but not with LuaTeX!.
[badtable.zip](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9968205/badtable.zip)
[badtablelua.pdf](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9968260/badtablelua.pdf)
[GOODxetex.zip](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9968273/GOODxetex.zip)

**Comment by FrankMittelbach** [comment]
sorry can you be a bit more precise on what is bad or good? What I see is that your Goodxetex.zip shows a .tex file that doesn't correspond to the .pdf as far as I can see. I honestly have no idea why badtablelua.pdf is supposed to be bad either.

**Comment by jsbien** [comment]
> your Goodxetex.zip shows a .tex file that doesn't correspond to the .pdf

I double checked, this **is** the PDF corresponding to the .tex file.
The correct output is best represented by fntsample:
[Junicode15p-sample.pdf](https://github.com/FrankMittelbach/fmitex-unicodefonttable/files/9972555/Junicode15p-sample.pdf)

**Comment by FrankMittelbach** [comment]
Ah, I see. I first tried to run it with luatex which shows this huge private area ...

Looks to me like a bug in the engine, all the package does is to ask "is there  a glyph in that particular slot?" and if so it typesets it. Obviously xetex and luatex see totally different data when looking at that font.

@zauguin do you perhaps see if there is an issue on the luatex side?

**Comment by zauguin** [comment]
For the ConTeXt fontloader this is by design, you should get the normal table when enabling HarfBuzz mode. The ConTeXt team does not considers the private use planes to be useful for direct user input and therefore uses them for remappings.

**Comment by FrankMittelbach** [comment]
thanks @zauguin. So it should have been
```
 \displayfonttable
%  [range-start=F0000,range-end=F005F,
[range-start=F0000,range-end=FFFFF,
                    nostatistics,noheader,hex-digits=block]
                  {JunicodeTwoBeta-Regular.ttf}
                  [Renderer=Harfbuzz]
```
Guess that calls for a) some documentation  and b) possibly a test in unicodefonttable to check if the private area is requested (and luatex used) and  a warning. Is there an easy way to find out if a font is set up to use Harfbuzz?

**Comment by zauguin** [comment]
> Is there an easy way to find out if a font is set up to use Harfbuzz?

You can do something like `\directlua{token.put_next(token.create(font.getfont(font.current()).hb and '@firstoftwo' or '@secondoftwo'))}{Is using HarfBuzz}{Is not using HarfBuzz}`

**Comment by FrankMittelbach** [comment]
good, thanks, that works. And which blocks are a problem? just the one starting at F0000  or also others?

**Comment by zauguin** [comment]
> good, thanks, that works. And which blocks are a problem? just the one starting at F0000 or also others?

I think it's currently only plane 15 but it's probably safer to also avoid place 16 (so everything starting at `F0000`).

**Comment by FrankMittelbach** [comment]
I now test for the combination request for displaying codepoints above U+EFFFF, luatex but no harfbuzz and issue a warningg that this will lead to incorrect output. Will show up in the next distributed release.
